apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-airqo-measurements-consumer
  namespace: production
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: prod-airqo-measurements-consumer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prod-airqo-measurements-consumer
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: prod-airqo-measurements-consumer
        image: us.gcr.io/airqo-250220/prod-measurements-consumer:latest
        imagePullPolicy: Always
        resources: {}
          # requests:
          #   memory: 256Mi
          #   cpu: "200m"
          # limits:
          #   memory: 512Mi
          #   cpu: "800m"
        envFrom:
          - configMapRef:
              name: prod-airqo-measurements-consumer-config
