apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: airqo-streams-raw-device-measurements-topic 
  namespace: production
  labels:
    strimzi.io/cluster: prod-kafka-cluster
spec:
  topicName: airqo-streams-raw-device-measurements-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: airqo-streams-transformed-device-measurements-topic 
  namespace: production
  labels:
    strimzi.io/cluster: prod-kafka-cluster
spec:
  topicName: airqo-streams-transformed-device-measurements-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: airqo-streams-processed-device-measurements-topic 
  namespace: production
  labels:
    strimzi.io/cluster: prod-kafka-cluster
spec:
  topicName: airqo-streams-processed-device-measurements-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour 

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: airqo-streams-calibrated-device-measurements-topic 
  namespace: production
  labels:
    strimzi.io/cluster: prod-kafka-cluster
spec:
  topicName: airqo-streams-calibrated-device-measurements-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: datawarehouse-input-topic 
  namespace: production
  labels:
    strimzi.io/cluster: prod-kafka-cluster
spec:
  topicName: datawarehouse-input-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: datawarehouse-output-topic 
  namespace: production
  labels:
    strimzi.io/cluster: prod-kafka-cluster
spec:
  topicName: datawarehouse-output-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sites-weather-topic 
  namespace: production
  labels:
    strimzi.io/cluster: prod-kafka-cluster
spec:
  topicName: sites-weather-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000 # 1 day

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: app-insights-measurements-topic
  namespace: production
  labels:
    strimzi.io/cluster: prod-kafka-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 day
