apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: airqo-batch-transformed-device-measurements-topic 
  namespace: staging
  labels:
    strimzi.io/cluster: stage-kafka-cluster
spec:
  topicName: airqo-batch-transformed-device-measurements-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000
