apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: airqo-hourly-measurements-topic
  namespace: staging
  labels:
    strimzi.io/cluster: stage-kafka-cluster
spec:
  topicName: airqo-hourly-measurements-topic
  partitions: 3
  replicas: 1
  config:
    retention.ms: 10800000 # 3 hours
