apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: airqo-streams-raw-device-measurements-topic 
  namespace: staging
  labels:
    strimzi.io/cluster: stage-kafka-cluster
spec:
  topicName: airqo-streams-raw-device-measurements-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: airqo-streams-transformed-device-measurements-topic 
  namespace: staging
  labels:
    strimzi.io/cluster: stage-kafka-cluster
spec:
  topicName: airqo-streams-transformed-device-measurements-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: airqo-streams-processed-device-measurements-topic 
  namespace: staging
  labels:
    strimzi.io/cluster: stage-kafka-cluster
spec:
  topicName: airqo-streams-processed-device-measurements-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: airqo-streams-calibrated-device-measurements-topic 
  namespace: staging
  labels:
    strimzi.io/cluster: stage-kafka-cluster
spec:
  topicName: airqo-streams-calibrated-device-measurements-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: datawarehouse-input-topic 
  namespace: staging
  labels:
    strimzi.io/cluster: stage-kafka-cluster
spec:
  topicName: datawarehouse-input-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: datawarehouse-output-topic 
  namespace: staging
  labels:
    strimzi.io/cluster: stage-kafka-cluster
spec:
  topicName: datawarehouse-output-topic 
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: app-insights-measurements-topic
  namespace: staging
  labels:
    strimzi.io/cluster: stage-kafka-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 day

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: hourly-measurements-topic
  namespace: staging
  labels:
    strimzi.io/cluster: stage-kafka-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1 day
