apiVersion: v2
appVersion: "1.16.0"
description: AirQo Redis Server Helm Chart
name: airqo-redis-server
home: https://airqo.net
version: 0.1.0
maintainers:
  - name: AirQo
    email: support@airqo.net
    url: https://airqo.net
