- hosts: mongo_cluster_prod
  become: true
  vars:
    passphrase: "passphrase" # encrypt with ansible-vault
    auth_db: "admin"
    adminUser: "adminUser" # encrypt with ansible-vault
    adminPass: "adminPass" # encrypt with ansible-vault
    tgt_db: "tgt_db" # encrypt with ansible-vault
    userName: "userName" # encrypt with ansible-vault
    userPass: "userPass" # encrypt with ansible-vault
    roles: ["readWrite", "userAdmin"]
    new_shard:
      name: shard-prod
      server: shard-prod-1.europe-west1-b.c.airqo-250220.internal

  roles:
    - { role: isaackehle.ansible_mongodb, flags: ["install"] }
    - { role: isaackehle.ansible_mongodb, flags: ["save_config"] }
    - { role: isaackehle.ansible_mongodb, flags: ["reset_storage"] }
    - { role: isaackehle.ansible_mongodb, flags: ["configure_tls"] }
    - { role: isaackehle.ansible_mongodb, flags: ["init_replica_set"] }
    - { role: isaackehle.ansible_mongodb, flags: ["add_shard_to_cluster"] }
    - { role: isaackehle.ansible_mongodb, flags: ["create_database"] }
