apiVersion: v1
appVersion: "1.0"
name: batch-streams
type: application
description: A Helm chart for Kubernetes
home: https://airqo.net
version: 0.1.0
maintainers: 
  - name: AirQo
    email: support@airqo.net
    url: https://airqo.net
