apiVersion: v1
kind: Namespace
metadata:
  name: pipeline

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pipeline-quota
  namespace: pipeline
spec:
  hard:
    limits.cpu: 2000
    limits.memory: 4Gi
    resourcequotas: 1