###########################################################
# Start deployment of authentication service microservice
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-auth-service
  namespace: staging
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 3
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: airqo-auth-service
          image: us.gcr.io/airqo-250220/airqo-auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: airqo-auth-service

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-auth-service
  namespace: staging
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort

##################################################################
# Start data management microserive deployment and provisioning
##################################################################
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: airqo-data-mgt-service
  namespace: staging
  labels:
    app: airqo-data-mgt-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: airqo-data-mgt-service
    spec:
      containers:
        - name: airqo-data-mgt-service
          image: us.gcr.io/airqo-250220/airqo-data-mgt-service:latest

          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: airqo-data-mgt-service-svc
  namespace: staging
spec:
  selector:
    app: airqo-data-mgt-service

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002
  type: NodePort

###########################################################
# Start ML microserive deployment and provisioning
##########################################################
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: airqo-ml-service
  namespace: staging
  labels:
    app: airqo-ml-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: airqo-ml-service
    spec:
      containers:
        - name: airqo-ml-service
          image: us.gcr.io/airqo-250220/airqo-ml-service:latest

          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: airqo-ml-service-svc
  namespace: staging
spec:
  selector:
    app: airqo-ml-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30003
  type: NodePort
###################################################################
# Start analytics backend microserive deployment and provisioning
###################################################################
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: airqo-analytics-backend
  namespace: staging
  labels:
    app: airqo-analytics-backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: airqo-analytics-backend
    spec:
      containers:
        - name: airqo-analytics-backend
          image: us.gcr.io/airqo-250220/airqo-analytics-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: airqo-analytics-backend-svc
  namespace: staging
spec:
  selector:
    app: airqo-analytics-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30004
  type: NodePort
