hosts: all
become: yes
tasks:
  - name: create the 'ubuntu' user
    user: name={USERNAME} append=yes state=present createhome=yes shell=/bin/bash

  - name: allow 'ubuntu' to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      line: "{USERNAME} ALL=(ALL) NOPASSWD: ALL"
      validate: "visudo -cf %s"

  - name: set up authorized keys for the ubuntu user
    authorized_key: user={USERNAME} key="{{item}}"
    with_file:
      - ~/.ssh/id_rsa.pub
