###########################################################
# Start deployment of calibrate kafka connection - production
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-calibrate-kafka
  namespace: production
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: prod-calibrate-kafka
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: prod-calibrate-kafka
    spec:
      containers:
      - name: prod-calibrate-kafka
        image: us.gcr.io/airqo-250220/airqo-prod-calibrate-kafka:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: prod-calibrate-config
        resources: {}
