app:
  name: airqo-exceedance-job
  namespace: staging
  configmap: env-exceedance-staging

image:
  repository: gcr.io/airqo-250220/stage-airqo-exceedance-job
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: ""
