app:
  name: airqo-exceedance-job
  namespace: production
  configmap: env-exceedance-production
image:
  repository: eu.gcr.io/airqo-250220/airqo-exceedance-job
  tag: prod-5d0ceb9d-1699741804
nameOverride: ''
fullnameOverride: ''
