app:
  name: airqo-exceedance-job
  namespace: staging
  configmap: env-exceedance-staging
image:
  repository: eu.gcr.io/airqo-250220/stage-airqo-exceedance-job
  tag: stage-58b994c8-1711431364
nameOverride: ''
fullnameOverride: ''
