app:
  name: kcca-exceedance-job
  namespace: staging
  configmap: env-exceedance-production
image:
  repository: gcr.io/airqo-250220/kcca-exceedance-job
  tag: prod-be97077b-1670926260
nameOverride: ''
fullnameOverride: ''
