app:
  name: airqo-exceedance-job
  namespace: staging
  configmap: env-exceedance-staging
image:
  repository: eu.gcr.io/airqo-250220/stage-airqo-exceedance-job
  tag: stage-a93d73e8-1677156910
nameOverride: ''
fullnameOverride: ''
