app:
  name: kcca-exceedance-job
  namespace: production
  configmap: env-exceedance-production
image:
  repository: eu.gcr.io/airqo-250220/kcca-exceedance-job
  tag: prod-de1de137-1699389313
nameOverride: ''
fullnameOverride: ''
