app:
  name: kcca-exceedance-job
  namespace: production
  configmap: env-exceedance-production
image:
  repository: eu.gcr.io/airqo-250220/kcca-exceedance-job
  tag: prod-f441a57b-1702303458
nameOverride: ''
fullnameOverride: ''
