apiVersion: v2
appVersion: "1.16.0"
description: AirQo Prediction Helm Chart
name: airqo-predict-job
home: https://airqo.net
version: 0.1.0
maintainers:
  - name: AirQo
    email: support@airqo.net
    url: https://airqo.net
