apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
  labels:
    io.kompose.service: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
        io.kompose.service: {{ .Values.app.name }}
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
      labels:
        io.kompose.service: {{ .Values.app.name }}
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
          name: {{ .Values.app.name }}
          image: redis:7.2.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.app.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      restartPolicy: Always
