apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
  labels:
    io.kompose.service: {{ .Values.app.name }}
  name: "{{ .Values.app.name }}-svc"
  namespace: {{ .Values.app.namespace }}
spec:
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    io.kompose.service: {{ .Values.app.name }}
