app:
  name: airqo-stage-view-message-broker
  label: view-msg-brokr
  namespace: staging
  configmap: stage-view-message-broker-config
replicaCount: 2
image:
  repository: gcr.io/airqo-250220/airqo-stage-view-message-broker
  tag: stage-70d63c48-1670410417
nameOverride: ''
fullnameOverride: ''
podAnnotations:
  sidecar.istio.io/inject: 'false'
resources:
  limits:
    cpu: 50m
    memory: 600Mi
  requests:
    cpu: 10m
    memory: 400Mi
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 80
