app:
  name: airqo-view-message-broker
  label: view-msg-brokr
  namespace: production
  configmap: prod-view-message-broker-config
replicaCount: 2
image:
  repository: eu.gcr.io/airqo-250220/airqo-view-message-broker
  tag: prod-05283ddd-1686833455
nameOverride: ''
fullnameOverride: ''
podAnnotations:
  sidecar.istio.io/inject: 'false'
resources:
  limits:
    cpu: 100m
    memory: 400Mi
  requests:
    cpu: 10m
    memory: 200Mi
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 80
