- hosts: k8s_master
  become: true
  gather_facts: false
  tasks:
    - name: Create the remove node script on master
      template:
        src: templates/remove_hourly_preemptive_node.sh.j2
        dest: /root/remove_hourly_preemptive_node.sh
        mode: a+x

    - name: Create cronjob to run the remove_hourly_preemptive_node script at minute 8 of every hour
      cron:
        name: "Remove preemptive k8s node from cluster"
        minute: "8"
        job: "/bin/bash /root/remove_hourly_preemptive_node.sh"

    - name: Get join command with a token that expires in 30 days (720 hours)
      shell: kubeadm token create --print-join-command --ttl 720h
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: hourly_preemptive_node
  become: true
  tasks:
    - name: Create the add node and reset node scripts on preemptive worker
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: a+x
      with_items:
        - {
            src: templates/join_k8s_cluster.sh.j2,
            dest: /root/join_k8s_cluster.sh,
          }
        - {
            src: templates/leave_k8s_cluster.sh.j2,
            dest: /root/leave_k8s_cluster.sh,
          }

    - name: Create cronjob to run the join_k8s_cluster script at minute 57 of every hour
      cron:
        name: "Add node to k8s cluster"
        minute: "57"
        job: "sudo /bin/bash /root/join_k8s_cluster.sh"

    - name: Create cronjob to run the leave_k8s_cluster script at minute 9 of every hour
      cron:
        name: "Reset k8s node"
        minute: "9"
        job: "/bin/bash /root/leave_k8s_cluster.sh"
