apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: airqo-calibrate-job
  namespace: staging
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  schedule: "@hourly"
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      name: airqo-calibrate-job
    spec:
      template:
        spec:
          containers:
            - image: us.gcr.io/airqo-250220/stage-calibrate-job:latest
              imagePullPolicy: Always
              name: airqo-calibrate-job
              env:
                - name: BOOTSTRAP_SERVERS
                  value: stage-kafka-cluster-kafka-bootstrap:9092
                - name: OUTPUT_TOPIC
                  value: hourly-measurements-topic
                - name: SCHEMA_REGISTRY_URL
                  value: http://stage-schema-registry-svc:8081
                - name: AIRQO_BASE_URL
                  value: https://staging-platform.airqo.net/api/v1/
                - name: TIMEOUT
                  value: "20"
                - name: HOURS
                  value: "1"
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
