apiVersion: batch/v1
kind: CronJob
metadata:
  name: prod-events-notifs-job
  namespace: production
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: true
  schedule: "30 * * * *"
  jobTemplate:
    metadata:
      name: prod-events-notifs-job
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          containers:
            - name: prod-events-notifs-job
              image: eu.gcr.io/airqo-250220/airqo-events-notifs-job:latest
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: 256Mi
                  cpu: 200m
                limits:
                  memory: 512Mi
                  cpu: "1"
              envFrom:
                - configMapRef:
                    name: prod-events-notifs-cronjob-config
