apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: stage-events-notifs-job
  namespace: staging
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "@hourly"
  jobTemplate:
    metadata:
      name: stage-events-notifs-job
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          containers:
          - name: stage-events-notifs-job
            image: us.gcr.io/airqo-250220/airqo-stage-events-notifs-job:latest
            imagePullPolicy: Always
            resources:
              requests:
                memory: 256Mi
                cpu: 200m
              limits:
                memory: 512Mi
                cpu: "1"
            envFrom:
              - configMapRef:
                  name: stage-events-notifs-cronjob-config
