apiVersion: v1
appVersion: "1.0"
description: AirQo Analytics Helm Chart
name: airqo-analytics-api
home: https://airqo.net
version: 0.1.0
maintainers: 
  - name: AirQo
    email: support@airqo.net
    url: https://airqo.net
