apiVersion: batch/v1
kind: CronJob
metadata:
  name: airqo-predict-job
  namespace: production
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "0 * * * *"
  jobTemplate:
    metadata:
      name: airqo-predict-job
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          containers:
          - name: airqo-predict-job
            image: us.gcr.io/airqo-250220/airqo-predict-job:latest
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: env-predict-job-production
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                cpu: 2000m
                memory: 1Gi
          volumes:
            - name: config-volume
              configMap:
                name: predict-job-config-files
