# values for airqo-prediction-api.
env:
  deployment_name: airqo-dev-prediction-api
  service_name: airqo-dev-prediction-api-svc
  labels: prediction-api
  secret: dev-prediction-secret

replicaCount: 2

image:
  repository: airqo-dev-prediction-api
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  nodePort: 32003
  targetPort: 5000
  port: 5000

ingress:
  enabled: false

nodeSelector: {}
resources: {}
affinity: {}
torelations: {}


## Application level settings  
appMode: development