apiVersion: v1
appVersion: "1.0"
description: AirQo Workflows Helm Chart for AKS
name: airqo-workflows
home: https://airqo.net
version: 0.1.0
maintainers:
  - name: AirQo
    email: support@airqo.net
    url: https://airqo.net
