###########################################################
# Start deployment of data-warehouse microservice - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-stage-datawarehouse-api
  namespace: staging
spec:
  selector:
    matchLabels:
      app: sta-datawarehouse-api
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sta-datawarehouse-api
    spec:
      containers:
        - name: datawarehouse
          image: us.gcr.io/airqo-250220/airqo-stage-datawarehouse-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 4001
          #   initialDelaySecond: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          resources:
            requests:
              memory: 256Mi
              cpu: "500m"
            limits:
              memory: 1Gi
              cpu: "2000m"
          envFrom:
            - configMapRef:
                name: stage-datawarehouse-api-config
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: stage-datawarehouse-api-config-files

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-stage-datawarehouse-api-svc
  namespace: staging
spec:
  selector:
    app: sta-datawarehouse-api
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 31111
  type: NodePort