###########################################################
# Start deployment of KCCA raw device measurements streams application - Staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-kcca-raw-measurements-stream
  namespace: staging
spec:
  selector:
    matchLabels:
      app: stage-kcca-raw-measurements-stream
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: stage-kcca-raw-measurements-stream
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: stage-airqo-raw-measurements-stream
          image: us.gcr.io/airqo-250220/stage-raw-device-measurements-stream:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: "200m"
            limits:
              memory: 700Mi
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: stage-kcca-raw-measurements-stream-config

